# # This workflow is for CI/CD of the frontend application.

# Nombre del workflow: CI/CD Frontend
name: CI/CD Frontend
# Controla lo que se va a ejecutar en el workflow.
# En este caso,
on:
  push:
    branches:
      [release, develop]
  pull_request:
    branches: 
      [release, develop]
jobs: 
  sistema-ventas-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sistema-ventas-web
    steps:
      - name: Checkout repository # Clona el repositorio
        uses: actions/checkout@v4

      - name: Setup Node.js # usar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.0 # Versión de Node.js

      - name: Cache node_modules # cargar cache de node_modules, para reducir el tiempo de instalación
        id: cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies # Instalar dependencias
      # No ejecutar si no hay cambios en node_modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        